In [ ]:
import pandas as _hex_pandas
import datetime as _hex_datetime
import json as _hex_json

In [ ]:
hex_scheduled = _hex_json.loads("false")

In [ ]:
hex_user_email = _hex_json.loads("\"example-user@example.com\"")

In [ ]:
hex_run_context = _hex_json.loads("\"logic\"")

In [ ]:
hex_timezone = _hex_json.loads("\"US/Eastern\"")

In [ ]:
hex_project_id = _hex_json.loads("\"5ffaa5cd-d050-4591-ab86-ea2d990dd028\"")

In [ ]:
hex_project_name = _hex_json.loads("\"python web scraping assignment\"")

In [ ]:
hex_status = _hex_json.loads("\"\"")

In [ ]:
hex_categories = _hex_json.loads("[]")

In [ ]:
hex_color_palette = _hex_json.loads("[\"#4C78A8\",\"#F58518\",\"#E45756\",\"#72B7B2\",\"#54A24B\",\"#EECA3B\",\"#B279A2\",\"#FF9DA6\",\"#9D755D\",\"#BAB0AC\"]")

In [ ]:
import requests 
import pandas as pd
from bs4 import BeautifulSoup
url = "https://webpages.charlotte.edu/mscipion/"
r = requests.get(url)
print(r)
soup = BeautifulSoup(r.text, "lxml")
table = soup.find("table")
headers = table.find_all("th")
print(headers)

titles = []
for i in headers:
    title = i.text 
    titles.append(title)
print(titles)
df = pd.DataFrame(columns=titles)
print(df)
rows = table.find_all("tr")
rows[1:2]

<Response [200]>
[<th>Student</th>, <th>Favourite Computer Language</th>, <th>Years of Experience</th>]
['Student', 'Favourite Computer Language', 'Years of Experience']
Empty DataFrame
Columns: [Student, Favourite Computer Language, Years of Experience]
Index: []

[<tr>
 <td>Fred</td>
 <td>Kotlin</td>
 <td>4</td>
 </tr>]

In [ ]:
for i in rows[1:]:
    data = i.find_all("td")
    row = [tr.text for tr in data]
    l = len(df)
    df.loc[l]=row

df.head(10)

,Student,Favourite Computer Language,Years of Experience
0,Fred,Kotlin,4
1,Paula,Python,2
2,Ernst,Java,7
3,Isabel,C++,3
4,Tony,Pearl,7
5,Maria,Cobol,15
6,Fred,Kotlin,4
7,Paula,Python,2
8,Ernst,Java,7
9,Isabel,C++,3